version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      
      # Create android emulator v24
      - run:
          name: Create avd
          command: |
            sdkmanager --update && sdkmanager "system-images;android-21;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n test_device -k "system-images;android-21;default;armeabi-v7a"
      - run:
          name: Start emulator
          command: emulator -avd test_device -no-audio -no-window
          background: true

      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Building the repo
          command: ./gradlew build

      - run:
          name: Run Unit Tests
          command: ./gradlew lint test

      - run:
          name: Wait for emulator
          command: |
            chmod +x android-wait-for-emulator.sh
            ./android-wait-for-emulator.sh
            adb devices

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82

      - run:
          name: Instrumentation testing
          command: ./gradlew connectedCheck

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/reports
          destination: reports

      # https://circleci.com/docs/2.0/configuration-reference/#store_test_results test should be in the same directory
      - run:
          name: Prepare test results
          command: |
            mv app/build/outputs/androidTest-results/connected app/build/outputs/androidTest-results/UI_Tests
            mv app/build/outputs/androidTest-results/UI_Tests app/build/test-results

      - store_test_results:
          path: app/build/test-results
